CREATE TABLE [dbo].[Carts]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [IdUser] UNIQUEIDENTIFIER NOT NULL, 
    [DateCreated] DATETIME NOT NULL, 
    CONSTRAINT [FK_Cart_ToUsers] FOREIGN KEY (IdUser) REFERENCES Users(Id)
)